export const CONFIG = {
  GENETIC: {
    DEFAULT_POPULATION_SIZE: 100,
    DEFAULT_MUTATION_RATE: 0.2,
    ELITISM_RATIO: 0.15,
  },
  IMAGE: {
    DEFAULT_BLUR: 0,
    DEFAULT_THRESHOLD: 130,
    MAX_DOT_COUNT: 200000,
    RECOMMENDED_DOTS_PER_IMPORTANCE_POINT: 0.035,
    RECOMMENDED_DOTS_PER_BLACK_PIXEL: 0.02,
    MAX_RECOMMENDED_DOT_PERCENTAGE: 0.04,
  },
};

export const CANVAS_IDS = {
  IMAGE: "imgCanvas",
  BLACK_WHITE: "bwCanvas",
  EVOLUTION: "evolCanvas",
};
